

services:
  server:
    build:
      context: .
    ports:
      - 3333:3000
    volumes:
      - .:/app
    environment:
        - DATABASE_URL=postgresql://postgres:docker@database:5432/guaruba-payments-db
        - API_URL=${API_URL}
        - HASH_SECRET=${HASH_SECRET}
        - BACKEND_SECRET_KEY=${BACKEND_SECRET_KEY}
        - BACKEND_PUBLIC_KEY=${BACKEND_PUBLIC_KEY}
        - SENTRY_DSN=${SENTRY_DSN}
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - guaruba-payments-net
    command: bun run dev

  database:
    restart: always
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: guaruba-payments-db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - guaruba-payments_ms_pg_data:/bitnami/postgresql
    networks:
        - guaruba-payments-net

volumes:
  guaruba-payments_ms_pg_data:

networks:
  guaruba-payments-net: